// Generated by scripts/prepare-assets.ts. Do not edit by hand.
export const assets = {
  "truthScale": {
    "mostlyTrue": "/assets/generated/truth-scale/mostly-true-384.webp",
    "mixed": "/assets/generated/truth-scale/mixed-384.webp",
    "mostlyFalse": "/assets/generated/truth-scale/mostly-false-384.webp",
    "insufficient": "/assets/generated/truth-scale/mixed-384.webp"
  },
  "billTypes": {
    "schoolMeals": "/assets/generated/bill-types/school-meals-384.webp",
    "spending": "/assets/generated/bill-types/spending-384.webp",
    "defense": "/assets/generated/bill-types/defense-384.webp",
    "education": "/assets/generated/bill-types/education-384.webp",
    "healthcare": "/assets/generated/bill-types/healthcare-384.webp",
    "environment": "/assets/generated/bill-types/environment-384.webp",
    "infrastructure": "/assets/generated/bill-types/infrastructure-384.webp",
    "transportation": "/assets/generated/bill-types/transportation-384.webp",
    "housing": "/assets/generated/bill-types/infrastructure-384.webp",
    "publicSafety": "/assets/generated/bill-types/defense-384.webp",
    "technology": "/assets/generated/bill-types/education-384.webp",
    "immigration": "/assets/generated/bill-types/immigration-384.webp",
    "taxation": "/assets/generated/bill-types/spending-384.webp",
    "energy": "/assets/generated/bill-types/environment-384.webp",
    "other": "/assets/generated/bill-types/school-meals-384.webp"
  },
  "government": {
    "house": "/assets/generated/government/house-symbol-384.webp",
    "senate": "/assets/generated/government/house-symbol-384.webp",
    "supremeCourt": "/assets/generated/government/supreme-court-symbol-384.webp",
    "executive": "/assets/generated/government/congress-symbol-384.webp",
    "congress": "/assets/generated/government/congress-symbol-384.webp"
  },
  "agencies": {
    "dhs": "/assets/generated/agencies/public-safety-symbol-384.webp",
    "cia": "/assets/generated/agencies/navigation-symbol-384.webp",
    "fbi": "/assets/generated/agencies/public-safety-symbol-384.webp",
    "ice": "/assets/generated/agencies/public-safety-symbol-384.webp",
    "doj": "/assets/generated/agencies/navigation-symbol-384.webp",
    "state": "/assets/generated/agencies/navigation-symbol-384.webp",
    "dod": "/assets/generated/agencies/navigation-symbol-384.webp",
    "ssa": "/assets/generated/agencies/navigation-symbol-384.webp",
    "epa": "/assets/generated/agencies/public-safety-symbol-384.webp",
    "nasa": "/assets/generated/agencies/navigation-symbol-384.webp",
    "cdc": "/assets/generated/agencies/public-safety-symbol-384.webp",
    "irs": "/assets/generated/agencies/navigation-symbol-384.webp"
  },
  "ui": {
    "streak": "/assets/generated/ui/claim-check-symbol-384.webp",
    "xp": "/assets/generated/ui/claim-check-symbol-384.webp",
    "source": "/assets/generated/ui/claim-check-symbol-384.webp",
    "quiz": "/assets/generated/ui/claim-check-symbol-384.webp",
    "privacy": "/assets/generated/ui/claim-check-symbol-384.webp",
    "claimCheck": "/assets/generated/ui/claim-check-symbol-384.webp",
    "ballot": "/assets/generated/ui/claim-check-symbol-384.webp",
    "vote": "/assets/generated/ui/claim-check-symbol-384.webp"
  }
} as const;

export type AssetRegistry = typeof assets;
export type AssetGroup = keyof AssetRegistry;
